"""Add roadmap model

Revision ID: 3ed132852651
Revises: da0b908b13f4
Create Date: 2026-01-30 18:14:49.790923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed132852651'
down_revision: Union[str, Sequence[str], None] = 'da0b908b13f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'UNLOCKED', 'COMPLETED', name='daystatus'), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_progress_id'), 'daily_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_progress_id'), table_name='daily_progress')
    op.drop_table('daily_progress')
    # ### end Alembic commands ###
