"""update_group_session_date_column

Revision ID: 57af98936c6b
Revises: 84902d580d35
Create Date: 2026-06-07 18:29:24.838652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57af98936c6b'
down_revision: Union[str, Sequence[str], None] = '84902d580d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_session_participants_session_id'), table_name='group_session_participants')
    op.drop_index(op.f('ix_group_session_participants_student_id'), table_name='group_session_participants')
    op.add_column('group_sessions', sa.Column('session_date', sa.String(length=10), nullable=False))
    op.drop_index(op.f('ix_group_sessions_expert_id'), table_name='group_sessions')
    op.drop_column('group_sessions', 'day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_sessions', sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_group_sessions_expert_id'), 'group_sessions', ['expert_id'], unique=False)
    op.drop_column('group_sessions', 'session_date')
    op.create_index(op.f('ix_group_session_participants_student_id'), 'group_session_participants', ['student_id'], unique=False)
    op.create_index(op.f('ix_group_session_participants_session_id'), 'group_session_participants', ['session_id'], unique=False)
    # ### end Alembic commands ###
