"""audit_schema

Revision ID: 686e8aa7174f
Revises: b43176ffdf24
Create Date: 2026-05-26 23:46:01.453219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '686e8aa7174f'
down_revision: Union[str, Sequence[str], None] = 'b43176ffdf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    if 'account_actions' in inspector.get_table_names():
        op.drop_table('account_actions')
    op.execute("DROP TYPE IF EXISTS accountactiontype;")
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_table('mbti_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_a_text', sa.Text(), nullable=True),
    sa.Column('option_b_text', sa.Text(), nullable=True),
    sa.Column('dimension', sa.String(length=5), nullable=False),
    sa.Column('option_a_value', sa.String(length=5), nullable=False),
    sa.Column('option_b_value', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_index(op.f('ix_mbti_questions_id'), 'mbti_questions', ['id'], unique=False)
    op.create_table('mbti_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('vietnamese_title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pros', sa.JSON(), nullable=False),
    sa.Column('cons', sa.JSON(), nullable=False),
    sa.Column('population_pct', sa.String(length=20), nullable=True),
    sa.Column('suggested_careers', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_mbti_types_id'), 'mbti_types', ['id'], unique=False)
    op.create_table('accountaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SUSPEND_EXPERT', 'UNSUSPEND_EXPERT', 'BAN_USER', 'UNBAN_USER', name='accountactiontype'), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountaction_id'), 'accountaction', ['id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='supportstatus'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_table('user_mbti_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mbti_code', sa.String(length=4), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('score_e', sa.Integer(), nullable=False),
    sa.Column('score_i', sa.Integer(), nullable=False),
    sa.Column('score_s', sa.Integer(), nullable=False),
    sa.Column('score_n', sa.Integer(), nullable=False),
    sa.Column('score_t', sa.Integer(), nullable=False),
    sa.Column('score_f', sa.Integer(), nullable=False),
    sa.Column('score_j', sa.Integer(), nullable=False),
    sa.Column('score_p', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mbti_results_id'), 'user_mbti_results', ['id'], unique=False)
    op.drop_constraint(op.f('blacklist_email_key'), 'blacklist', type_='unique')
    op.drop_index(op.f('ix_blacklist_email'), table_name='blacklist')
    op.create_index(op.f('ix_blacklist_email'), 'blacklist', ['email'], unique=True)
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scoring_logic', sa.JSON(), nullable=True))
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('questions_assessment_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'assessments', ['assessment_id'], ['id'])
    op.drop_column('questions', 'category')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'account_status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::userstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'account_status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::userstatus"))
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('questions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_assessment_id_fkey'), 'questions', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('questions', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'scoring_logic')
    op.drop_column('questions', 'order')
    op.drop_column('questions', 'question_type')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_email'), table_name='blacklist')
    op.create_index(op.f('ix_blacklist_email'), 'blacklist', ['email'], unique=False)
    op.create_unique_constraint(op.f('blacklist_email_key'), 'blacklist', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('account_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', postgresql.ENUM('SUSPEND_EXPERT', 'UNSUSPEND_EXPERT', 'BAN_USER', 'UNBAN_USER', name='accountactiontype'), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('account_actions_admin_id_fkey')),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], name=op.f('account_actions_target_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_actions_pkey'))
    )
    op.drop_index(op.f('ix_user_mbti_results_id'), table_name='user_mbti_results')
    op.drop_table('user_mbti_results')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_accountaction_id'), table_name='accountaction')
    op.drop_table('accountaction')
    op.drop_index(op.f('ix_mbti_types_id'), table_name='mbti_types')
    op.drop_table('mbti_types')
    op.drop_index(op.f('ix_mbti_questions_id'), table_name='mbti_questions')
    op.drop_table('mbti_questions')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
