"""Rename Transaction to PaymentTransaction

Revision ID: 793575c937cf
Revises: 9cd6a9bff51f
Create Date: 2026-01-30 18:34:26.547998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793575c937cf'
down_revision: Union[str, Sequence[str], None] = '9cd6a9bff51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
