"""add_group_session_tables

Revision ID: 84902d580d35
Revises: b56d1bd1b998
Create Date: 2026-06-07 14:39:40.205595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84902d580d35'
down_revision: Union[str, Sequence[str], None] = 'b56d1bd1b998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('price_per_participant', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'ONGOING', 'COMPLETED', 'CANCELLED', name='groupsessionstatus'), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_sessions_expert_id'), 'group_sessions', ['expert_id'], unique=False)
    op.create_index(op.f('ix_group_sessions_id'), 'group_sessions', ['id'], unique=False)
    op.create_table('group_session_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='groupparticipantstatus'), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('student_note', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['group_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_session_participants_id'), 'group_session_participants', ['id'], unique=False)
    op.create_index(op.f('ix_group_session_participants_session_id'), 'group_session_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_group_session_participants_student_id'), 'group_session_participants', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_session_participants_student_id'), table_name='group_session_participants')
    op.drop_index(op.f('ix_group_session_participants_session_id'), table_name='group_session_participants')
    op.drop_index(op.f('ix_group_session_participants_id'), table_name='group_session_participants')
    op.drop_table('group_session_participants')
    op.drop_index(op.f('ix_group_sessions_id'), table_name='group_sessions')
    op.drop_index(op.f('ix_group_sessions_expert_id'), table_name='group_sessions')
    op.drop_table('group_sessions')
    # ### end Alembic commands ###
