"""Add tags to expert

Revision ID: 9cd6a9bff51f
Revises: 3ed132852651
Create Date: 2026-01-30 18:15:37.559289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd6a9bff51f'
down_revision: Union[str, Sequence[str], None] = '3ed132852651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_profiles', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_profiles', 'tags')
    # ### end Alembic commands ###
