"""Add payout_reference to transactions

Revision ID: a64e3e821b3f
Revises: be585d3a2ca7
Create Date: 2026-04-22 10:24:30.975869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64e3e821b3f'
down_revision: Union[str, Sequence[str], None] = 'be585d3a2ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('transactions', sa.Column('payout_reference', sa.String(), nullable=True))
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_created_at'), 'user', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('transactions', 'payout_reference')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
