"""uc19_expert_bank_info_and_withdrawal_status

Revision ID: a7585980d7eb
Revises: 5941d55c73dc
Create Date: 2026-03-08 15:04:26.948214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7585980d7eb'
down_revision: Union[str, Sequence[str], None] = '5941d55c73dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_table('email_logs')
    op.add_column('expert_profiles', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('expert_profiles', sa.Column('bank_account', sa.String(), nullable=True))
    op.add_column('expert_profiles', sa.Column('bank_holder_name', sa.String(), nullable=True))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.add_column('transactions', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bank_account', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bank_holder_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('admin_note', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Add new enum values for UC-19 (PostgreSQL requires ALTER TYPE)
    op.execute("ALTER TYPE transactionstatus ADD VALUE IF NOT EXISTS 'PENDING_PAYOUT'")
    op.execute("ALTER TYPE transactionstatus ADD VALUE IF NOT EXISTS 'REJECTED_PAYOUT'")
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'admin_note')
    op.drop_column('transactions', 'bank_holder_name')
    op.drop_column('transactions', 'bank_account')
    op.drop_column('transactions', 'bank_name')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('expert_profiles', 'bank_holder_name')
    op.drop_column('expert_profiles', 'bank_account')
    op.drop_column('expert_profiles', 'bank_name')
    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_logs_pkey'))
    )
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    # ### end Alembic commands ###
