"""Add expert cancellation penalty quiz and roadmap history

Revision ID: adfefd4e28df
Revises: a64e3e821b3f
Create Date: 2026-04-28 11:23:10.493356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfefd4e28df'
down_revision: Union[str, Sequence[str], None] = 'a64e3e821b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first for PostgreSQL
    quiz_status_enum = sa.Enum('NONE', 'PENDING', 'COMPLETED', name='quizstatus')
    quiz_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('roadmap_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('is_premium', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_history_id'), 'roadmap_history', ['id'], unique=False)
    op.create_table('expert_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_quizzes_id'), 'expert_quizzes', ['id'], unique=False)
    op.create_table('booking_quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['expert_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_quiz_responses_id'), 'booking_quiz_responses', ['id'], unique=False)
    op.add_column('bookings', sa.Column('quiz_status', sa.Enum('NONE', 'PENDING', 'COMPLETED', name='quizstatus'), nullable=False, server_default='NONE'))
    op.add_column('expert_profiles', sa.Column('cancellation_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('expert_profiles', sa.Column('late_cancellation_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_profiles', 'late_cancellation_count')
    op.drop_column('expert_profiles', 'cancellation_count')
    op.drop_column('bookings', 'quiz_status')
    
    quiz_status_enum = sa.Enum('NONE', 'PENDING', 'COMPLETED', name='quizstatus')
    quiz_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_booking_quiz_responses_id'), table_name='booking_quiz_responses')
    op.drop_table('booking_quiz_responses')
    op.drop_index(op.f('ix_expert_quizzes_id'), table_name='expert_quizzes')
    op.drop_table('expert_quizzes')
    op.drop_index(op.f('ix_roadmap_history_id'), table_name='roadmap_history')
    op.drop_table('roadmap_history')
    # ### end Alembic commands ###
