"""Add ExpertPortfolio tables

Revision ID: b43176ffdf24
Revises: daaa00964c97
Create Date: 2026-05-26 10:10:28.226261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43176ffdf24'
down_revision: Union[str, Sequence[str], None] = 'daaa00964c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ARTICLE', 'RESEARCH_PAPER', 'DOCUMENT', name='posttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='poststatus'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_posts_id'), 'expert_posts', ['id'], unique=False)
    op.create_index(op.f('ix_expert_posts_slug'), 'expert_posts', ['slug'], unique=True)
    op.create_table('post_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['expert_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_attachments_id'), 'post_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_attachments_id'), table_name='post_attachments')
    op.drop_table('post_attachments')
    op.drop_index(op.f('ix_expert_posts_slug'), table_name='expert_posts')
    op.drop_index(op.f('ix_expert_posts_id'), table_name='expert_posts')
    op.drop_table('expert_posts')
    # ### end Alembic commands ###
