"""add max_participants to ExpertAvailability

Revision ID: b56d1bd1b998
Revises: e9d0c323859e
Create Date: 2026-05-27 09:23:05.815104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56d1bd1b998'
down_revision: Union[str, Sequence[str], None] = 'e9d0c323859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_availabilities', sa.Column('max_participants', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_availabilities', 'max_participants')
    # ### end Alembic commands ###
