#!/bin/bash
# ==============================================================================
# VOCA AUTOMATED DEPLOYMENT SCRIPT (Bản cải tiến)
# ==============================================================================
# Script này tự động hóa việc thu thập key, tạo các file .env cho Backend và Frontend,
# kiểm tra xác thực GitHub, commit và push mã nguồn lên GitHub.
#
# Cách chạy: bash scripts/deploy.sh
# ==============================================================================

set -e

# Hàm in tiêu đề
print_header() {
    echo "========================================================================"
    echo "         VOCA AUTOMATED DEPLOYMENT & ENV GENERATOR SCRIPT"
    echo "========================================================================"
    echo "Hãy chuẩn bị sẵn các thông tin từ Supabase, Upstash và Resend."
    echo "Nếu giá trị có chứa ký tự đặc biệt (ví dụ mật khẩu DB), script sẽ tự mã hóa."
    echo "------------------------------------------------------------------------"
}

print_header

# ------------------------------------------------------------------------------
# 1. Thu thập thông tin từ user
# ------------------------------------------------------------------------------
echo "--- 1. Cấu hình Supabase (Database & API) ---"
read -p "🔑 Nhập Supabase Project Ref ID (ví dụ: jjbicqwwnwtjnhucessm): " SB_REF
while [ -z "$SB_REF" ]; do
    read -p "❌ Project Ref ID không được để trống. Nhập lại: " SB_REF
done

read -s -p "🔑 Nhập Supabase Database Password: " SB_PWD
echo ""
while [ -z "$SB_PWD" ]; do
    read -s -p "❌ Mật khẩu DB không được để trống. Nhập lại: " SB_PWD
    echo ""
done

# Tự động hóa URL mã hóa mật khẩu sử dụng Python
SB_PWD_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote_plus('''$SB_PWD'''))")

read -p "🔑 Nhập Supabase Pooler Host [mặc định: aws-1-ap-southeast-1.pooler.supabase.com]: " SB_POOLER_HOST
SB_POOLER_HOST=${SB_POOLER_HOST:-aws-1-ap-southeast-1.pooler.supabase.com}

read -p "🔑 Nhập Supabase Anon Key (Public): " SB_ANON
while [ -z "$SB_ANON" ]; do
    read -p "❌ Anon Key không được để trống. Nhập lại: " SB_ANON
done

read -p "🔑 Nhập Supabase Service Role Key (Secret): " SB_SVC
while [ -z "$SB_SVC" ]; do
    read -p "❌ Service Role Key không được để trống. Nhập lại: " SB_SVC
done

echo ""
echo "--- 2. Cấu hình Upstash (Redis Cache) ---"
read -p "🔑 Nhập Upstash Redis URL (phải bắt đầu bằng rediss://): " REDIS_URL
while [[ ! "$REDIS_URL" =~ ^rediss:// ]]; do
    echo "❌ Định dạng Redis URL không hợp lệ! Phải bắt đầu bằng 'rediss://' (có bảo mật TLS)."
    read -p "Nhập lại Upstash Redis URL: " REDIS_URL
done

echo ""
echo "--- 3. Cấu hình Resend (Email Service) ---"
read -p "🔑 Nhập Resend API Key (ví dụ: re_xxxxxxxx): " RESEND_KEY
while [ -z "$RESEND_KEY" ]; do
    read -p "❌ Resend API Key không được để trống. Nhập lại: " RESEND_KEY
done

read -p "🔑 Nhập Email Gửi (FROM_EMAIL) [mặc định: onboarding@resend.dev]: " FROM_EMAIL
FROM_EMAIL=${FROM_EMAIL:-onboarding@resend.dev}

echo ""
echo "--- 4. Cấu hình Endpoint của Backend trên Frontend ---"
read -p "🔑 Nhập URL Backend API [mặc định: https://voca-backend-hizk.onrender.com/api/v1]: " BACKEND_API_URL
BACKEND_API_URL=${BACKEND_API_URL:-https://voca-backend-hizk.onrender.com/api/v1}

# Dựng DATABASE_URL dạng pooler cổng 6543
DATABASE_URL="postgresql://postgres.${SB_REF}:${SB_PWD_ENCODED}@${SB_POOLER_HOST}:6543/postgres?prepared_statement_cache_size=0"

# ------------------------------------------------------------------------------
# 2. Sinh cấu hình cho Backend (.env)
# ------------------------------------------------------------------------------
echo ""
echo "⚙️ Đang khởi tạo file cấu hình backend/.env..."

cat <<EOF > backend/.env
# ==============================================================================
# AUTO-GENERATED BY deploy.sh
# Môi trường: Production (Render)
# ==============================================================================
PROJECT_NAME="CareerPath AI"
DATABASE_URL="${DATABASE_URL}"
REDIS_URL="${REDIS_URL}"
SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
ALGORITHM="HS256"
ACCESS_TOKEN_EXPIRE_MINUTES=1440
ALLOW_MOCK_LOGIN=false

# Cấu hình Email (Resend REST API)
EMAILS_ENABLED=true
RESEND_KEY="${RESEND_KEY}"
EMAILS_FROM_EMAIL="${FROM_EMAIL}"
EMAILS_FROM_NAME="VOCA System"

# Cấu hình Supabase (Dành cho các logic xử lý tệp tin hoặc xác thực ở backend)
SUPABASE_URL="https://${SB_REF}.supabase.co"
SUPABASE_ANON_KEY="${SB_ANON}"
SUPABASE_SERVICE_ROLE_KEY="${SB_SVC}"
EOF

echo "✅ Đã tạo xong file backend/.env thành công!"

# ------------------------------------------------------------------------------
# 3. Sinh cấu hình cho Frontend (.env.local)
# ------------------------------------------------------------------------------
echo "⚙️ Đang khởi tạo file cấu hình frontend/.env.local..."

cat <<EOF > frontend/.env.local
# ==============================================================================
# AUTO-GENERATED BY deploy.sh
# Môi trường: Local & Production (Vercel)
# ==============================================================================
NEXT_PUBLIC_API_URL="${BACKEND_API_URL}"
NEXT_PUBLIC_GA_ID="G-9VLJXPDV86"
NEXT_PUBLIC_GOOGLE_CLIENT_ID="365753397530-5bfa36k7s58h2r261md10r87bak5gc2s.apps.googleusercontent.com"

# Supabase Integration
NEXT_PUBLIC_SUPABASE_URL="https://${SB_REF}.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${SB_ANON}"
EOF

echo "✅ Đã tạo xong file frontend/.env.local thành công!"

# ------------------------------------------------------------------------------
# 4. Tự động hóa đẩy code lên GitHub
# ------------------------------------------------------------------------------
echo ""
echo "🚀 Chuẩn bị đẩy code lên GitHub..."

# Kiểm tra git repository
if [ ! -d ".git" ]; then
    echo "⚠️ Dự án chưa khởi tạo Git! Đang khởi tạo..."
    git init
    git branch -M main
fi

# Kiểm tra CLI GitHub (gh) để hỗ trợ đăng nhập
if ! command -v gh &> /dev/null; then
    echo "⚠️ Không tìm thấy GitHub CLI (gh) trên hệ thống."
    echo "👉 Bạn hãy chắc chắn đã đăng nhập Git bằng SSH/HTTPS trước khi tiếp tục."
else
    echo "🔍 Kiểm tra trạng thái đăng nhập GitHub CLI (gh)..."
    if ! gh auth status &> /dev/null; then
        echo "------------------------------------------------------------------------"
        echo "👉 Bạn chưa đăng nhập GitHub. Vui lòng làm theo hướng dẫn của GitHub CLI:"
        echo "------------------------------------------------------------------------"
        gh auth login
    else
        echo "✅ Bạn đã đăng nhập GitHub CLI thành công!"
    fi
fi

# Commit và đẩy mã nguồn lên GitHub
echo "📦 Đang thực hiện commit các tệp cấu hình..."
# Lưu ý: Thông thường .env không đẩy lên Git, nhưng script này cập nhật các tệp liên quan cấu hình như render.yaml hoặc tài liệu.
git add render.yaml docs/GO_LIVE_RUNBOOK.md scripts/deploy.sh || true
# Cố gắng đẩy nếu có sự thay đổi
git commit -m "chore: Cập nhật cấu hình triển khai và script tự động hóa" || true

echo "📤 Đang đẩy mã nguồn lên nhánh main..."
if git push origin main; then
    echo "✅ Đã đẩy mã nguồn lên GitHub thành công!"
else
    echo "⚠️ Không thể tự động push lên GitHub. Vui lòng kiểm tra lại remote và chạy thủ công: git push origin main"
fi

# ------------------------------------------------------------------------------
# 5. Hướng dẫn các bước tiếp theo
# ------------------------------------------------------------------------------
echo ""
echo "========================================================================"
echo "🎉 HOÀN TẤT KỊCH BẢN THIẾT LẬP MÔI TRƯỜNG!"
echo "========================================================================"
echo "Tiếp theo bạn cần làm:"
echo ""
echo "1️⃣  FRONTEND (Vercel):"
echo "    - Truy cập Vercel Dashboard (vercel.com)"
echo "    - Nhập repository VOCA của bạn."
echo "    - Chọn 'Root Directory' là 'frontend'."
echo "    - Thêm các biến môi trường sau vào Vercel:"
echo "      * NEXT_PUBLIC_API_URL = ${BACKEND_API_URL}"
echo "      * NEXT_PUBLIC_SUPABASE_URL = https://${SB_REF}.supabase.co"
echo "      * NEXT_PUBLIC_SUPABASE_ANON_KEY = ${SB_ANON}"
echo "    - Nhấn Deploy!"
echo ""
echo "2️⃣  BACKEND (Render):"
echo "    - Truy cập Render Dashboard (render.com)"
echo "    - Nhấp New -> Blueprint."
echo "    - Kết nối với repository GitHub VOCA."
echo "    - Render sẽ tự động đọc cấu hình của 'render.yaml'."
echo "    - Điền các biến môi trường thực tế (DATABASE_URL, REDIS_URL, RESEND_KEY, v.v.) vào mục environment."
echo ""
echo "3️⃣  BẢO MẬT DATABASE (Supabase RLS):"
echo "    - Đọc file docs/GO_LIVE_RUNBOOK.md"
echo "    - Mở SQL Editor trên Supabase Dashboard và chạy lệnh SQL kích hoạt Row-Level Security."
echo "========================================================================"
